//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
typedef struct SvrCh__Config__PTofCls__LMCPublisher 
  {
    CHMETH *pMeth;
    _Config_ dData;
    SVRDSC *pDsc;
  } SvrCh__Config__PTofCls__LMCPublisher;

typedef struct CltCh__Config__PTofCls__LMCPublisher 
  {
    struct SvrCh__Config__PTofCls__LMCPublisher *pCh;
    _Config_ dData;
    SVRCHCMD *pCmd;
  } CltCh__Config__PTofCls__LMCPublisher;

typedef struct SvrCh__POSFLAGS 
  {
    CHMETH *pMeth;
    _POSFLAGS dData;
    SVRDSC *pDsc;
  } SvrCh__POSFLAGS;

typedef struct CltCh__POSFLAGS 
  {
    struct SvrCh__POSFLAGS *pCh;
    _POSFLAGS dData;
    SVRCHCMD *pCmd;
  } CltCh__POSFLAGS;

typedef struct SvrCh_BDINT 
  {
    CHMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrCh_BDINT;

typedef struct CltCh_BDINT 
  {
    struct SvrCh_BDINT *pCh;
    BDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_BDINT;

typedef struct SvrCh_CanHwSwitchTxt_PTofCls_CanDriverBase 
  {
    CHMETH *pMeth;
    CanHwSwitchTxt dData;
    SVRDSC *pDsc;
  } SvrCh_CanHwSwitchTxt_PTofCls_CanDriverBase;

typedef struct CltCh_CanHwSwitchTxt_PTofCls_CanDriverBase 
  {
    struct SvrCh_CanHwSwitchTxt_PTofCls_CanDriverBase *pCh;
    CanHwSwitchTxt dData;
    SVRCHCMD *pCmd;
  } CltCh_CanHwSwitchTxt_PTofCls_CanDriverBase;

typedef struct SvrCh_cilPos 
  {
    CHMETH *pMeth;
    cilPos dData;
    SVRDSC *pDsc;
  } SvrCh_cilPos;

typedef struct CltCh_cilPos 
  {
    struct SvrCh_cilPos *pCh;
    cilPos dData;
    SVRCHCMD *pCmd;
  } CltCh_cilPos;

typedef struct SvrCh_DINT 
  {
    CHMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrCh_DINT;

typedef struct CltCh_DINT 
  {
    struct SvrCh_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltCh_DINT;

typedef struct SvrCh_eHMI_CmdPML 
  {
    CHMETH *pMeth;
    eHMI_CmdPML dData;
    SVRDSC *pDsc;
  } SvrCh_eHMI_CmdPML;

typedef struct CltCh_eHMI_CmdPML 
  {
    struct SvrCh_eHMI_CmdPML *pCh;
    eHMI_CmdPML dData;
    SVRCHCMD *pCmd;
  } CltCh_eHMI_CmdPML;

typedef struct SvrCh_eSimuState 
  {
    CHMETH *pMeth;
    eSimuState dData;
    SVRDSC *pDsc;
  } SvrCh_eSimuState;

typedef struct CltCh_eSimuState 
  {
    struct SvrCh_eSimuState *pCh;
    eSimuState dData;
    SVRCHCMD *pCmd;
  } CltCh_eSimuState;

typedef struct SvrCh_FeSetup 
  {
    CHMETH *pMeth;
    FeSetup dData;
    SVRDSC *pDsc;
  } SvrCh_FeSetup;

typedef struct CltCh_FeSetup 
  {
    struct SvrCh_FeSetup *pCh;
    FeSetup dData;
    SVRCHCMD *pCmd;
  } CltCh_FeSetup;

typedef struct SvrCh_HDINT 
  {
    CHMETH *pMeth;
    HDINT dData;
    SVRDSC *pDsc;
  } SvrCh_HDINT;

typedef struct CltCh_HDINT 
  {
    struct SvrCh_HDINT *pCh;
    HDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_HDINT;

typedef struct SvrCh_IO_State 
  {
    CHMETH *pMeth;
    IO_State dData;
    SVRDSC *pDsc;
  } SvrCh_IO_State;

typedef struct CltCh_IO_State 
  {
    struct SvrCh_IO_State *pCh;
    IO_State dData;
    SVRCHCMD *pCmd;
  } CltCh_IO_State;

typedef struct SvrCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster 
  {
    CHMETH *pMeth;
    t_SDCIPortMode dData;
    SVRDSC *pDsc;
  } SvrCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster;

typedef struct CltCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster 
  {
    struct SvrCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster *pCh;
    t_SDCIPortMode dData;
    SVRCHCMD *pCmd;
  } CltCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster;

typedef struct SvrCh_UDINT 
  {
    CHMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrCh_UDINT;

typedef struct CltCh_UDINT 
  {
    struct SvrCh_UDINT *pCh;
    UDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_UDINT;

typedef struct SvrChCmd_DINT 
  {
    CMDMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_DINT;

typedef struct CltChCmd__AlarmX0Para 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _AlarmX0Para *pCmd;
  } CltChCmd__AlarmX0Para;

typedef struct CltChCmd__AlarmX3ParaDer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _AlarmX3ParaDer *pCmd;
  } CltChCmd__AlarmX3ParaDer;

typedef struct SvrChCmd__LMCAXIS_OPMODE 
  {
    CMDMETH *pMeth;
    _LMCAXIS_OPMODE dData;
    SVRDSC *pDsc;
  } SvrChCmd__LMCAXIS_OPMODE;

typedef struct CltChCmd__AxisBase 
  {
    struct SvrChCmd__LMCAXIS_OPMODE *pCh;
    _LMCAXIS_OPMODE dData;
    _AxisBase *pCmd;
  } CltChCmd__AxisBase;

typedef struct SvrChCmd_t_e_VaranErrors 
  {
    CMDMETH *pMeth;
    t_e_VaranErrors dData;
    SVRDSC *pDsc;
  } SvrChCmd_t_e_VaranErrors;

typedef struct CltChCmd__BusInterfaceSdiasDriveMng 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    _BusInterfaceSdiasDriveMng *pCmd;
  } CltChCmd__BusInterfaceSdiasDriveMng;

typedef struct CltChCmd__Can 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Can *pCmd;
  } CltChCmd__Can;

typedef struct CltChCmd__CanLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _CanLib *pCmd;
  } CltChCmd__CanLib;

typedef struct SvrChCmd_iprStates 
  {
    CMDMETH *pMeth;
    iprStates dData;
    SVRDSC *pDsc;
  } SvrChCmd_iprStates;

typedef struct CltChCmd__DriveAxisBase 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    _DriveAxisBase *pCmd;
  } CltChCmd__DriveAxisBase;

typedef struct CltChCmd__DriveAxisSet 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _DriveAxisSet *pCmd;
  } CltChCmd__DriveAxisSet;

typedef struct CltChCmd__DriveMngBase 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    _DriveMngBase *pCmd;
  } CltChCmd__DriveMngBase;

typedef struct CltChCmd__DriveMotorPara 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    _DriveMotorPara *pCmd;
  } CltChCmd__DriveMotorPara;

typedef struct CltChCmd__DrivePositionPara 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    _DrivePositionPara *pCmd;
  } CltChCmd__DrivePositionPara;

typedef struct CltChCmd__DriveSpeedPara 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    _DriveSpeedPara *pCmd;
  } CltChCmd__DriveSpeedPara;

typedef struct CltChCmd__FileSys 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _FileSys *pCmd;
  } CltChCmd__FileSys;

typedef struct CltChCmd__Grafix 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Grafix *pCmd;
  } CltChCmd__Grafix;

typedef struct CltChCmd__Linker 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Linker *pCmd;
  } CltChCmd__Linker;

typedef struct CltChCmd__LMCABSEncoder 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCABSEncoder *pCmd;
  } CltChCmd__LMCABSEncoder;

typedef struct CltChCmd__LMCAxis 
  {
    struct SvrChCmd__LMCAXIS_OPMODE *pCh;
    _LMCAXIS_OPMODE dData;
    _LMCAxis *pCmd;
  } CltChCmd__LMCAxis;

typedef struct CltChCmd__LMCAxisBase 
  {
    struct SvrChCmd__LMCAXIS_OPMODE *pCh;
    _LMCAXIS_OPMODE dData;
    _LMCAxisBase *pCmd;
  } CltChCmd__LMCAxisBase;

typedef struct CltChCmd__LMCAxisRef 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisRef *pCmd;
  } CltChCmd__LMCAxisRef;

typedef struct CltChCmd__LMCAxisVis 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVis *pCmd;
  } CltChCmd__LMCAxisVis;

typedef struct CltChCmd__LMCAxisVisInt 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisInt *pCmd;
  } CltChCmd__LMCAxisVisInt;

typedef struct CltChCmd__LMCAxisVisLogHandle 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisLogHandle *pCmd;
  } CltChCmd__LMCAxisVisLogHandle;

typedef struct CltChCmd__LMCAxisVisLogViewer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisLogViewer *pCmd;
  } CltChCmd__LMCAxisVisLogViewer;

typedef struct CltChCmd__LMCAxisVisPara 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisPara *pCmd;
  } CltChCmd__LMCAxisVisPara;

typedef struct CltChCmd__LMCMathFunctions 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCMathFunctions *pCmd;
  } CltChCmd__LMCMathFunctions;

typedef struct SvrChCmd_ProfileCommandStatus 
  {
    CMDMETH *pMeth;
    ProfileCommandStatus dData;
    SVRDSC *pDsc;
  } SvrChCmd_ProfileCommandStatus;

typedef struct CltChCmd__LMCProfileBase 
  {
    struct SvrChCmd_ProfileCommandStatus *pCh;
    ProfileCommandStatus dData;
    _LMCProfileBase *pCmd;
  } CltChCmd__LMCProfileBase;

typedef struct CltChCmd__LMCProfileBuffer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileBuffer *pCmd;
  } CltChCmd__LMCProfileBuffer;

typedef struct CltChCmd__LMCProfileLog 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileLog *pCmd;
  } CltChCmd__LMCProfileLog;

typedef struct CltChCmd__LMCProfileVis 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileVis *pCmd;
  } CltChCmd__LMCProfileVis;

typedef struct CltChCmd__LMCProfileVisAxis 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileVisAxis *pCmd;
  } CltChCmd__LMCProfileVisAxis;

typedef struct CltChCmd__LMCProfileVisInt 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileVisInt *pCmd;
  } CltChCmd__LMCProfileVisInt;

typedef struct CltChCmd__LMCProfileVisMovePara 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileVisMovePara *pCmd;
  } CltChCmd__LMCProfileVisMovePara;

typedef struct CltChCmd__LMCPublisher 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCPublisher *pCmd;
  } CltChCmd__LMCPublisher;

typedef struct CltChCmd__LMCRefBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCRefBase *pCmd;
  } CltChCmd__LMCRefBase;

typedef struct CltChCmd__LMCSafety 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCSafety *pCmd;
  } CltChCmd__LMCSafety;

typedef struct CltChCmd__LMCTableBuffer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCTableBuffer *pCmd;
  } CltChCmd__LMCTableBuffer;

typedef struct CltChCmd__Lse 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Lse *pCmd;
  } CltChCmd__Lse;

typedef struct CltChCmd__MultiTask 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _MultiTask *pCmd;
  } CltChCmd__MultiTask;

typedef struct CltChCmd__OSKernel 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OSKernel *pCmd;
  } CltChCmd__OSKernel;

typedef struct CltChCmd__OsziLSEBackground 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OsziLSEBackground *pCmd;
  } CltChCmd__OsziLSEBackground;

typedef struct CltChCmd__SerLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _SerLib *pCmd;
  } CltChCmd__SerLib;

typedef struct CltChCmd__SerLibCSI 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _SerLibCSI *pCmd;
  } CltChCmd__SerLibCSI;

typedef struct CltChCmd__StdLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _StdLib *pCmd;
  } CltChCmd__StdLib;

typedef struct SvrChCmd_DATE_LSL 
  {
    CMDMETH *pMeth;
    DATE_LSL dData;
    SVRDSC *pDsc;
  } SvrChCmd_DATE_LSL;

typedef struct CltChCmd__SysDateTime2 
  {
    struct SvrChCmd_DATE_LSL *pCh;
    DATE_LSL dData;
    _SysDateTime2 *pCmd;
  } CltChCmd__SysDateTime2;

typedef struct CltChCmd__SysMsg 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _SysMsg *pCmd;
  } CltChCmd__SysMsg;

typedef struct CltChCmd__TaskObjectControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _TaskObjectControl *pCmd;
  } CltChCmd__TaskObjectControl;

typedef struct CltChCmd__VaranDriveBase 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    _VaranDriveBase *pCmd;
  } CltChCmd__VaranDriveBase;

typedef struct CltChCmd_ASCII_BIN 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ASCII_BIN *pCmd;
  } CltChCmd_ASCII_BIN;

typedef struct CltChCmd_AssemblyDbV2 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    AssemblyDbV2 *pCmd;
  } CltChCmd_AssemblyDbV2;

typedef struct CltChCmd_AssemblyOneProdRuleV2 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    AssemblyOneProdRuleV2 *pCmd;
  } CltChCmd_AssemblyOneProdRuleV2;

typedef struct SvrChCmd_BDINT 
  {
    CMDMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_BDINT;

typedef struct CltChCmd_BDINT 
  {
    struct SvrChCmd_BDINT *pCh;
    BDINT dData;
    SVRCHCMD *pCmd;
  } CltChCmd_BDINT;

typedef struct CltChCmd_calcComplete 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    calcComplete *pCmd;
  } CltChCmd_calcComplete;

typedef struct CltChCmd_calcOperationListV2 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    calcOperationListV2 *pCmd;
  } CltChCmd_calcOperationListV2;

typedef struct CltChCmd_CanDriverBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    CanDriverBase *pCmd;
  } CltChCmd_CanDriverBase;

typedef struct CltChCmd_CanOpenBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    CanOpenBase *pCmd;
  } CltChCmd_CanOpenBase;

typedef struct CltChCmd_cmBlower 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    cmBlower *pCmd;
  } CltChCmd_cmBlower;

typedef struct CltChCmd_cmCil 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    cmCil *pCmd;
  } CltChCmd_cmCil;

typedef struct CltChCmd_cmMotor 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    cmMotor *pCmd;
  } CltChCmd_cmMotor;

typedef struct CltChCmd_cmMultipleCil 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    cmMultipleCil *pCmd;
  } CltChCmd_cmMultipleCil;

typedef struct CltChCmd_cmServo 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    cmServo *pCmd;
  } CltChCmd_cmServo;

typedef struct CltChCmd_cntrAmount 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    cntrAmount *pCmd;
  } CltChCmd_cntrAmount;

typedef struct CltChCmd_cntrDistance 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    cntrDistance *pCmd;
  } CltChCmd_cntrDistance;

typedef struct CltChCmd_ConfigDefBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ConfigDefBase *pCmd;
  } CltChCmd_ConfigDefBase;

typedef struct CltChCmd_Controller 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Controller *pCmd;
  } CltChCmd_Controller;

typedef struct CltChCmd_convertOperationListToSLinesV2 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    convertOperationListToSLinesV2 *pCmd;
  } CltChCmd_convertOperationListToSLinesV2;

typedef struct SvrChCmd_UDINT 
  {
    CMDMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_UDINT;

typedef struct CltChCmd_CriticalSection 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    CriticalSection *pCmd;
  } CltChCmd_CriticalSection;

typedef struct SvrChCmd_IO_State 
  {
    CMDMETH *pMeth;
    IO_State dData;
    SVRDSC *pDsc;
  } SvrChCmd_IO_State;

typedef struct CltChCmd_CSI022_Base 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    CSI022_Base *pCmd;
  } CltChCmd_CSI022_Base;

typedef struct CltChCmd_dbSettings 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    dbSettings *pCmd;
  } CltChCmd_dbSettings;

typedef struct CltChCmd_DiasMaster 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMaster *pCmd;
  } CltChCmd_DiasMaster;

typedef struct CltChCmd_DiasMasterC 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMasterC *pCmd;
  } CltChCmd_DiasMasterC;

typedef struct CltChCmd_DiasMasterPostScan 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMasterPostScan *pCmd;
  } CltChCmd_DiasMasterPostScan;

typedef struct CltChCmd_DINT 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltChCmd_DINT;

typedef struct CltChCmd_EditString 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    EditString *pCmd;
  } CltChCmd_EditString;

typedef struct CltChCmd_EEPROM 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    EEPROM *pCmd;
  } CltChCmd_EEPROM;

typedef struct CltChCmd_emBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    emBase *pCmd;
  } CltChCmd_emBase;

typedef struct CltChCmd_emPressureRoller 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    emPressureRoller *pCmd;
  } CltChCmd_emPressureRoller;

typedef struct CltChCmd_emWagon 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    emWagon *pCmd;
  } CltChCmd_emWagon;

typedef struct CltChCmd_File_IO 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    File_IO *pCmd;
  } CltChCmd_File_IO;

typedef struct CltChCmd_FileBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    FileBase *pCmd;
  } CltChCmd_FileBase;

typedef struct CltChCmd_GetBroadCastData 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GetBroadCastData *pCmd;
  } CltChCmd_GetBroadCastData;

typedef struct CltChCmd_GlobalList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GlobalList *pCmd;
  } CltChCmd_GlobalList;

typedef struct CltChCmd_Graphic 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Graphic *pCmd;
  } CltChCmd_Graphic;

typedef struct CltChCmd_Hub_Base 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Hub_Base *pCmd;
  } CltChCmd_Hub_Base;

typedef struct CltChCmd_Hub_Base_Root 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Hub_Base_Root *pCmd;
  } CltChCmd_Hub_Base_Root;

typedef struct CltChCmd_HwcLogging 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwcLogging *pCmd;
  } CltChCmd_HwcLogging;

typedef struct CltChCmd_HwControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwControl *pCmd;
  } CltChCmd_HwControl;

typedef struct CltChCmd_HwControlBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwControlBase *pCmd;
  } CltChCmd_HwControlBase;

typedef struct CltChCmd_HWKVarSizeFIFO 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HWKVarSizeFIFO *pCmd;
  } CltChCmd_HWKVarSizeFIFO;

typedef struct CltChCmd_HWRtPostScan 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HWRtPostScan *pCmd;
  } CltChCmd_HWRtPostScan;

typedef struct CltChCmd_I2CCDIAS 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    I2CCDIAS *pCmd;
  } CltChCmd_I2CCDIAS;

typedef struct CltChCmd_Lees10Ingangenin 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Lees10Ingangenin *pCmd;
  } CltChCmd_Lees10Ingangenin;

typedef struct CltChCmd_Logic_Or_2 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Logic_Or_2 *pCmd;
  } CltChCmd_Logic_Or_2;

typedef struct CltChCmd_mainControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    mainControl *pCmd;
  } CltChCmd_mainControl;

typedef struct CltChCmd_MerkerEx 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    MerkerEx *pCmd;
  } CltChCmd_MerkerEx;

typedef struct CltChCmd_MillingProgsDbV2 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    MillingProgsDbV2 *pCmd;
  } CltChCmd_MillingProgsDbV2;

typedef struct CltChCmd_MillLine 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    MillLine *pCmd;
  } CltChCmd_MillLine;

typedef struct CltChCmd_MillPlane 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    MillPlane *pCmd;
  } CltChCmd_MillPlane;

typedef struct CltChCmd_MillPlanes 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    MillPlanes *pCmd;
  } CltChCmd_MillPlanes;

typedef struct CltChCmd_MotorParaBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    MotorParaBase *pCmd;
  } CltChCmd_MotorParaBase;

typedef struct CltChCmd_OperationDataV2 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    OperationDataV2 *pCmd;
  } CltChCmd_OperationDataV2;

typedef struct CltChCmd_OperationLineV2 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    OperationLineV2 *pCmd;
  } CltChCmd_OperationLineV2;

typedef struct CltChCmd_ProductsDbV2 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ProductsDbV2 *pCmd;
  } CltChCmd_ProductsDbV2;

typedef struct CltChCmd_ProfileCommandStatus 
  {
    struct SvrChCmd_ProfileCommandStatus *pCh;
    ProfileCommandStatus dData;
    SVRCHCMD *pCmd;
  } CltChCmd_ProfileCommandStatus;

typedef struct CltChCmd_Ram 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Ram *pCmd;
  } CltChCmd_Ram;

typedef struct CltChCmd_RAMex 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RAMex *pCmd;
  } CltChCmd_RAMex;

typedef struct CltChCmd_RamFile 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RamFile *pCmd;
  } CltChCmd_RamFile;

typedef struct CltChCmd_RamSregels 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    RamSregels *pCmd;
  } CltChCmd_RamSregels;

typedef struct CltChCmd_readInGlobalList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    readInGlobalList *pCmd;
  } CltChCmd_readInGlobalList;

typedef struct CltChCmd_SafetyManager 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SafetyManager *pCmd;
  } CltChCmd_SafetyManager;

typedef struct CltChCmd_SCBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SCBase *pCmd;
  } CltChCmd_SCBase;

typedef struct CltChCmd_ScreenCtrl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ScreenCtrl *pCmd;
  } CltChCmd_ScreenCtrl;

typedef struct CltChCmd_SDCIClassIFM2330 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SDCIClassIFM2330 *pCmd;
  } CltChCmd_SDCIClassIFM2330;

typedef struct CltChCmd_SDCIClassIFM_AL2401 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SDCIClassIFM_AL2401 *pCmd;
  } CltChCmd_SDCIClassIFM_AL2401;

typedef struct CltChCmd_SDCIDevice 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SDCIDevice *pCmd;
  } CltChCmd_SDCIDevice;

typedef struct CltChCmd_SDCIDevice_AsyncPara 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    SDCIDevice_AsyncPara *pCmd;
  } CltChCmd_SDCIDevice_AsyncPara;

typedef struct CltChCmd_SDCIPort 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SDCIPort *pCmd;
  } CltChCmd_SDCIPort;

typedef struct CltChCmd_SdiasBase 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SdiasBase *pCmd;
  } CltChCmd_SdiasBase;

typedef struct CltChCmd_SdiasHubBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SdiasHubBase *pCmd;
  } CltChCmd_SdiasHubBase;

typedef struct CltChCmd_SdiasManager 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SdiasManager *pCmd;
  } CltChCmd_SdiasManager;

typedef struct CltChCmd_SdiasSafetyManager 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SdiasSafetyManager *pCmd;
  } CltChCmd_SdiasSafetyManager;

typedef struct CltChCmd_SdiasSafetyManagerFSoE 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SdiasSafetyManagerFSoE *pCmd;
  } CltChCmd_SdiasSafetyManagerFSoE;

typedef struct CltChCmd_SdiasUartHandler 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SdiasUartHandler *pCmd;
  } CltChCmd_SdiasUartHandler;

typedef struct CltChCmd_SigCLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SigCLib *pCmd;
  } CltChCmd_SigCLib;

typedef struct CltChCmd_sLineHandler 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    sLineHandler *pCmd;
  } CltChCmd_sLineHandler;

typedef struct CltChCmd_String 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    String *pCmd;
  } CltChCmd_String;

typedef struct CltChCmd_StringInternal 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    StringInternal *pCmd;
  } CltChCmd_StringInternal;

typedef struct CltChCmd_StringRAM 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    StringRAM *pCmd;
  } CltChCmd_StringRAM;

typedef struct CltChCmd_SyncCall 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    SyncCall *pCmd;
  } CltChCmd_SyncCall;

typedef struct CltChCmd_System 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    System *pCmd;
  } CltChCmd_System;

typedef struct CltChCmd_t_e_VaranErrors 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SVRCHCMD *pCmd;
  } CltChCmd_t_e_VaranErrors;

typedef struct CltChCmd_tMyBDintTODint 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    tMyBDintTODint *pCmd;
  } CltChCmd_tMyBDintTODint;

typedef struct CltChCmd_ToolsDb 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ToolsDb *pCmd;
  } CltChCmd_ToolsDb;

typedef struct CltChCmd_Uitv_Regel 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Uitv_Regel *pCmd;
  } CltChCmd_Uitv_Regel;

typedef struct CltChCmd_unitBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    unitBase *pCmd;
  } CltChCmd_unitBase;

typedef struct CltChCmd_Varan_Base 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    Varan_Base *pCmd;
  } CltChCmd_Varan_Base;

typedef struct CltChCmd_VaranManager_Base 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    VaranManager_Base *pCmd;
  } CltChCmd_VaranManager_Base;

typedef struct CltChCmd_WatchdogDias 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    WatchdogDias *pCmd;
  } CltChCmd_WatchdogDias;

typedef struct SvrCh__CommandList_PTofCls__LMCAxisBase 
  {
    CHMETH *pMeth;
    _CommandList dData;
    SVRDSC *pDsc;
  } SvrCh__CommandList_PTofCls__LMCAxisBase;

typedef struct SvrCh__DRIVETYPE 
  {
    CHMETH *pMeth;
    _DRIVETYPE dData;
    SVRDSC *pDsc;
  } SvrCh__DRIVETYPE;

typedef struct SvrCh__FSM_UDP_ERROR_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _FSM_UDP_ERROR dData;
    SVRDSC *pDsc;
  } SvrCh__FSM_UDP_ERROR_PTofCls_SafetyUDP;

typedef struct SvrCh__FSM_UDP_USER_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _FSM_UDP_USER dData;
    SVRDSC *pDsc;
  } SvrCh__FSM_UDP_USER_PTofCls_SafetyUDP;

typedef struct SvrCh__I_HC_Type 
  {
    CHMETH *pMeth;
    _I_HC_Type dData;
    SVRDSC *pDsc;
  } SvrCh__I_HC_Type;

typedef struct SvrCh__INITSTEPS_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _INITSTEPS dData;
    SVRDSC *pDsc;
  } SvrCh__INITSTEPS_PTofCls_SafetyUDP;

typedef struct SvrCh__LMCAXIS_CMDERROR 
  {
    CHMETH *pMeth;
    _LMCAXIS_CMDERROR dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_CMDERROR;

typedef struct SvrCh__LMCAXIS_ERROR 
  {
    CHMETH *pMeth;
    _LMCAXIS_ERROR dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_ERROR;

typedef struct SvrCh__LMCAXIS_ERROR_CONFIG 
  {
    CHMETH *pMeth;
    _LMCAXIS_ERROR_CONFIG dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_ERROR_CONFIG;

typedef struct SvrCh__LMCAXIS_MOVE_RELATIVE_MODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_MOVE_RELATIVE_MODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_MOVE_RELATIVE_MODE;

typedef struct SvrCh__LMCAXIS_MOVEDIRECTION 
  {
    CHMETH *pMeth;
    _LMCAXIS_MOVEDIRECTION dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_MOVEDIRECTION;

typedef struct SvrCh__LMCAXIS_MOVEPROFILE 
  {
    CHMETH *pMeth;
    _LMCAXIS_MOVEPROFILE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_MOVEPROFILE;

typedef struct SvrCh__LMCAXIS_OPMODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_OPMODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_OPMODE;

typedef struct SvrCh__LMCAXIS_POSMODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_POSMODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_POSMODE;

typedef struct SvrCh__LMCAXIS_POWER_OFF_MODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_POWER_OFF_MODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_POWER_OFF_MODE;

typedef struct SvrCh__LMCAXIS_REFMODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_REFMODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_REFMODE;

typedef struct SvrCh__LMCAXIS_SETPARAMETER 
  {
    CHMETH *pMeth;
    _LMCAXIS_SETPARAMETER dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_SETPARAMETER;

typedef struct SvrCh__LMCAXIS_SETPOSITION 
  {
    CHMETH *pMeth;
    _LMCAXIS_SETPOSITION dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_SETPOSITION;

typedef struct SvrCh__LMCAXIS_SETSWENDPOS 
  {
    CHMETH *pMeth;
    _LMCAXIS_SETSWENDPOS dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_SETSWENDPOS;

typedef struct SvrCh__LMCAXIS_STATUS 
  {
    CHMETH *pMeth;
    _LMCAXIS_STATUS dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_STATUS;

typedef struct SvrCh__LMCCONTROLLERTYPE 
  {
    CHMETH *pMeth;
    _LMCCONTROLLERTYPE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCCONTROLLERTYPE;

typedef struct SvrCh__LMCPROF_OPMODE 
  {
    CHMETH *pMeth;
    _LMCPROF_OPMODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROF_OPMODE;

typedef struct SvrCh__LMCPROFCIRCLEDEF 
  {
    CHMETH *pMeth;
    _LMCPROFCIRCLEDEF dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFCIRCLEDEF;

typedef struct SvrCh__LMCPROFCMDCONFIG 
  {
    CHMETH *pMeth;
    _LMCPROFCMDCONFIG dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFCMDCONFIG;

typedef struct SvrCh__LMCPROFCMDTYPES 
  {
    CHMETH *pMeth;
    _LMCPROFCMDTYPES dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFCMDTYPES;

typedef struct SvrCh__LMCPROFERRORTYPES 
  {
    CHMETH *pMeth;
    _LMCPROFERRORTYPES dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFERRORTYPES;

typedef struct SvrCh__LMCPROFERRWARNCONFIG 
  {
    CHMETH *pMeth;
    _LMCPROFERRWARNCONFIG dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFERRWARNCONFIG;

typedef struct SvrCh__LMCPROFILESTATES 
  {
    CHMETH *pMeth;
    _LMCPROFILESTATES dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFILESTATES;

typedef struct SvrCh__LMCPROFMOVEPROFILE 
  {
    CHMETH *pMeth;
    _LMCPROFMOVEPROFILE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFMOVEPROFILE;

typedef struct SvrCh__LMCPROFPARAMETER 
  {
    CHMETH *pMeth;
    _LMCPROFPARAMETER dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFPARAMETER;

typedef struct SvrCh__LMCPROFPARAMETERAXIS 
  {
    CHMETH *pMeth;
    _LMCPROFPARAMETERAXIS dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFPARAMETERAXIS;

typedef struct SvrCh__LMCPROFPARAMETERGROUPS 
  {
    CHMETH *pMeth;
    _LMCPROFPARAMETERGROUPS dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFPARAMETERGROUPS;

typedef struct SvrCh__LMCPROFTRANSMODES 
  {
    CHMETH *pMeth;
    _LMCPROFTRANSMODES dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFTRANSMODES;

typedef struct SvrCh__SDDAXISSTATE 
  {
    CHMETH *pMeth;
    _SDDAXISSTATE dData;
    SVRDSC *pDsc;
  } SvrCh__SDDAXISSTATE;

typedef struct SvrCh__SDDUSERCMD 
  {
    CHMETH *pMeth;
    _SDDUSERCMD dData;
    SVRDSC *pDsc;
  } SvrCh__SDDUSERCMD;

typedef struct SvrCh_CanDeviceStateTxt 
  {
    CHMETH *pMeth;
    CanDeviceStateTxt dData;
    SVRDSC *pDsc;
  } SvrCh_CanDeviceStateTxt;

typedef struct SvrCh_DS402_Control 
  {
    CHMETH *pMeth;
    DS402_Control dData;
    SVRDSC *pDsc;
  } SvrCh_DS402_Control;

typedef struct SvrCh_DS402_State 
  {
    CHMETH *pMeth;
    DS402_State dData;
    SVRDSC *pDsc;
  } SvrCh_DS402_State;

typedef struct SvrCh_eMillToolComp 
  {
    CHMETH *pMeth;
    eMillToolComp dData;
    SVRDSC *pDsc;
  } SvrCh_eMillToolComp;

typedef struct SvrCh_eMillType 
  {
    CHMETH *pMeth;
    eMillType dData;
    SVRDSC *pDsc;
  } SvrCh_eMillType;

typedef struct SvrCh_eModePML 
  {
    CHMETH *pMeth;
    eModePML dData;
    SVRDSC *pDsc;
  } SvrCh_eModePML;

typedef struct SvrCh_eStatePML 
  {
    CHMETH *pMeth;
    eStatePML dData;
    SVRDSC *pDsc;
  } SvrCh_eStatePML;

typedef struct SvrCh_eTypeMillProg 
  {
    CHMETH *pMeth;
    eTypeMillProg dData;
    SVRDSC *pDsc;
  } SvrCh_eTypeMillProg;

typedef struct SvrCh_EventTypeTxt_PTofCls_SCBase 
  {
    CHMETH *pMeth;
    EventTypeTxt dData;
    SVRDSC *pDsc;
  } SvrCh_EventTypeTxt_PTofCls_SCBase;

typedef struct SvrCh_feedPos 
  {
    CHMETH *pMeth;
    feedPos dData;
    SVRDSC *pDsc;
  } SvrCh_feedPos;

typedef struct SvrCh_motorPos 
  {
    CHMETH *pMeth;
    motorPos dData;
    SVRDSC *pDsc;
  } SvrCh_motorPos;

typedef struct SvrCh_pcPlaneType 
  {
    CHMETH *pMeth;
    pcPlaneType dData;
    SVRDSC *pDsc;
  } SvrCh_pcPlaneType;

typedef struct SvrCh_pcUnitTypes 
  {
    CHMETH *pMeth;
    pcUnitTypes dData;
    SVRDSC *pDsc;
  } SvrCh_pcUnitTypes;

typedef struct SvrCh_SafetyConfigStateType 
  {
    CHMETH *pMeth;
    SafetyConfigStateType dData;
    SVRDSC *pDsc;
  } SvrCh_SafetyConfigStateType;

typedef struct SvrCh_servoPos 
  {
    CHMETH *pMeth;
    servoPos dData;
    SVRDSC *pDsc;
  } SvrCh_servoPos;

typedef struct SvrCh_t_bdOptionBits_PTofCls_SdiasUartHandler 
  {
    CHMETH *pMeth;
    t_bdOptionBits dData;
    SVRDSC *pDsc;
  } SvrCh_t_bdOptionBits_PTofCls_SdiasUartHandler;

typedef struct SvrCh_t_e_VaranErrors 
  {
    CHMETH *pMeth;
    t_e_VaranErrors dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_VaranErrors;

typedef struct SvrCh_t_FaultFlagSvr_PTofCls_SDCIDevice 
  {
    CHMETH *pMeth;
    t_FaultFlagSvr dData;
    SVRDSC *pDsc;
  } SvrCh_t_FaultFlagSvr_PTofCls_SDCIDevice;

typedef struct SvrCh_t_SDCIPortStateBits_PTofCls_SdiasSDCIMaster 
  {
    CHMETH *pMeth;
    t_SDCIPortStateBits dData;
    SVRDSC *pDsc;
  } SvrCh_t_SDCIPortStateBits_PTofCls_SdiasSDCIMaster;

typedef struct SvrCh_t_SDCIRetCode_PTofCls_SdiasSDCIMaster 
  {
    CHMETH *pMeth;
    t_SDCIRetCode dData;
    SVRDSC *pDsc;
  } SvrCh_t_SDCIRetCode_PTofCls_SdiasSDCIMaster;

typedef struct SvrCh_t_SDIAS_ErrorBits_AM221_PTofCls_AM221 
  {
    CHMETH *pMeth;
    t_SDIAS_ErrorBits_AM221 dData;
    SVRDSC *pDsc;
  } SvrCh_t_SDIAS_ErrorBits_AM221_PTofCls_AM221;

typedef struct SvrCh_t_SDIAS_ErrorBits_AM441_PTofCls_AM441 
  {
    CHMETH *pMeth;
    t_SDIAS_ErrorBits_AM441 dData;
    SVRDSC *pDsc;
  } SvrCh_t_SDIAS_ErrorBits_AM441_PTofCls_AM441;

typedef struct SvrCh_TIME_LSL 
  {
    CHMETH *pMeth;
    TIME_LSL dData;
    SVRDSC *pDsc;
  } SvrCh_TIME_LSL;

typedef struct SvrCh_tMyBDint 
  {
    CHMETH *pMeth;
    tMyBDint dData;
    SVRDSC *pDsc;
  } SvrCh_tMyBDint;

typedef struct SvrCh_Units 
  {
    CHMETH *pMeth;
    Units dData;
    SVRDSC *pDsc;
  } SvrCh_Units;

