//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
TYPE
  SvrCh__Config__PTofCls__LMCPublisher : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPublisher::_Config_;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh__Config__PTofCls__LMCPublisher : STRUCT
    pCh : ^SvrCh__Config__PTofCls__LMCPublisher;
    dData : _LMCPublisher::_Config_;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh__POSFLAGS : STRUCT
    pMeth : ^CHMETH;
    dData : _POSFLAGS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh__POSFLAGS : STRUCT
    pCh : ^SvrCh__POSFLAGS;
    dData : _POSFLAGS;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_BDINT : STRUCT
    pMeth : ^CHMETH;
    dData : BDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_BDINT : STRUCT
    pCh : ^SvrCh_BDINT;
    dData : BDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_CanHwSwitchTxt_PTofCls_CanDriverBase : STRUCT
    pMeth : ^CHMETH;
    dData : CanDriverBase::CanHwSwitchTxt;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_CanHwSwitchTxt_PTofCls_CanDriverBase : STRUCT
    pCh : ^SvrCh_CanHwSwitchTxt_PTofCls_CanDriverBase;
    dData : CanDriverBase::CanHwSwitchTxt;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_cilPos : STRUCT
    pMeth : ^CHMETH;
    dData : cilPos;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_cilPos : STRUCT
    pCh : ^SvrCh_cilPos;
    dData : cilPos;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_DINT : STRUCT
    pMeth : ^CHMETH;
    dData : DINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_DINT : STRUCT
    pCh : ^SvrCh_DINT;
    dData : DINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_eHMI_CmdPML : STRUCT
    pMeth : ^CHMETH;
    dData : eHMI_CmdPML;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_eHMI_CmdPML : STRUCT
    pCh : ^SvrCh_eHMI_CmdPML;
    dData : eHMI_CmdPML;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_eSimuState : STRUCT
    pMeth : ^CHMETH;
    dData : eSimuState;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_eSimuState : STRUCT
    pCh : ^SvrCh_eSimuState;
    dData : eSimuState;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_FeSetup : STRUCT
    pMeth : ^CHMETH;
    dData : FeSetup;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_FeSetup : STRUCT
    pCh : ^SvrCh_FeSetup;
    dData : FeSetup;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_HDINT : STRUCT
    pMeth : ^CHMETH;
    dData : HDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_HDINT : STRUCT
    pCh : ^SvrCh_HDINT;
    dData : HDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_IO_State : STRUCT
    pMeth : ^CHMETH;
    dData : IO_State;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_IO_State : STRUCT
    pCh : ^SvrCh_IO_State;
    dData : IO_State;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster : STRUCT
    pMeth : ^CHMETH;
    dData : SdiasSDCIMaster::t_SDCIPortMode;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster : STRUCT
    pCh : ^SvrCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster;
    dData : SdiasSDCIMaster::t_SDCIPortMode;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_UDINT : STRUCT
    pMeth : ^CHMETH;
    dData : UDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_UDINT : STRUCT
    pCh : ^SvrCh_UDINT;
    dData : UDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrChCmd_DINT : STRUCT
    pMeth : ^CMDMETH;
    dData : DINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__AlarmX0Para : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_AlarmX0Para;
  END_STRUCT;
  CltChCmd__AlarmX3ParaDer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_AlarmX3ParaDer;
  END_STRUCT;
  SvrChCmd__LMCAXIS_OPMODE : STRUCT
    pMeth : ^CMDMETH;
    dData : _LMCAXIS_OPMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__AxisBase : STRUCT
    pCh : ^SvrChCmd__LMCAXIS_OPMODE;
    dData : _LMCAXIS_OPMODE;
    pCmd : ^_AxisBase;
  END_STRUCT;
  SvrChCmd_t_e_VaranErrors : STRUCT
    pMeth : ^CMDMETH;
    dData : t_e_VaranErrors;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__BusInterfaceSdiasDriveMng : STRUCT
    pCh : ^SvrChCmd_t_e_VaranErrors;
    dData : t_e_VaranErrors;
    pCmd : ^_BusInterfaceSdiasDriveMng;
  END_STRUCT;
  CltChCmd__Can : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_Can;
  END_STRUCT;
  CltChCmd__CanLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_CanLib;
  END_STRUCT;
  SvrChCmd_iprStates : STRUCT
    pMeth : ^CMDMETH;
    dData : iprStates;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__DriveAxisBase : STRUCT
    pCh : ^SvrChCmd_iprStates;
    dData : iprStates;
    pCmd : ^_DriveAxisBase;
  END_STRUCT;
  CltChCmd__DriveAxisSet : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_DriveAxisSet;
  END_STRUCT;
  CltChCmd__DriveMngBase : STRUCT
    pCh : ^SvrChCmd_t_e_VaranErrors;
    dData : t_e_VaranErrors;
    pCmd : ^_DriveMngBase;
  END_STRUCT;
  CltChCmd__DriveMotorPara : STRUCT
    pCh : ^SvrChCmd_iprStates;
    dData : iprStates;
    pCmd : ^_DriveMotorPara;
  END_STRUCT;
  CltChCmd__DrivePositionPara : STRUCT
    pCh : ^SvrChCmd_iprStates;
    dData : iprStates;
    pCmd : ^_DrivePositionPara;
  END_STRUCT;
  CltChCmd__DriveSpeedPara : STRUCT
    pCh : ^SvrChCmd_iprStates;
    dData : iprStates;
    pCmd : ^_DriveSpeedPara;
  END_STRUCT;
  CltChCmd__FileSys : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_FileSys;
  END_STRUCT;
  CltChCmd__Grafix : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_Grafix;
  END_STRUCT;
  CltChCmd__Linker : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_Linker;
  END_STRUCT;
  CltChCmd__LMCABSEncoder : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCABSEncoder;
  END_STRUCT;
  CltChCmd__LMCAxis : STRUCT
    pCh : ^SvrChCmd__LMCAXIS_OPMODE;
    dData : _LMCAXIS_OPMODE;
    pCmd : ^_LMCAxis;
  END_STRUCT;
  CltChCmd__LMCAxisBase : STRUCT
    pCh : ^SvrChCmd__LMCAXIS_OPMODE;
    dData : _LMCAXIS_OPMODE;
    pCmd : ^_LMCAxisBase;
  END_STRUCT;
  CltChCmd__LMCAxisRef : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisRef;
  END_STRUCT;
  CltChCmd__LMCAxisVis : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVis;
  END_STRUCT;
  CltChCmd__LMCAxisVisInt : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisInt;
  END_STRUCT;
  CltChCmd__LMCAxisVisLogHandle : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisLogHandle;
  END_STRUCT;
  CltChCmd__LMCAxisVisLogViewer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisLogViewer;
  END_STRUCT;
  CltChCmd__LMCAxisVisPara : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisPara;
  END_STRUCT;
  CltChCmd__LMCMathFunctions : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCMathFunctions;
  END_STRUCT;
  SvrChCmd_ProfileCommandStatus : STRUCT
    pMeth : ^CMDMETH;
    dData : ProfileCommandStatus;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__LMCProfileBase : STRUCT
    pCh : ^SvrChCmd_ProfileCommandStatus;
    dData : ProfileCommandStatus;
    pCmd : ^_LMCProfileBase;
  END_STRUCT;
  CltChCmd__LMCProfileBuffer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileBuffer;
  END_STRUCT;
  CltChCmd__LMCProfileLog : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileLog;
  END_STRUCT;
  CltChCmd__LMCProfileVis : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVis;
  END_STRUCT;
  CltChCmd__LMCProfileVisAxis : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVisAxis;
  END_STRUCT;
  CltChCmd__LMCProfileVisInt : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVisInt;
  END_STRUCT;
  CltChCmd__LMCProfileVisMovePara : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVisMovePara;
  END_STRUCT;
  CltChCmd__LMCPublisher : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCPublisher;
  END_STRUCT;
  CltChCmd__LMCRefBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCRefBase;
  END_STRUCT;
  CltChCmd__LMCSafety : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCSafety;
  END_STRUCT;
  CltChCmd__LMCTableBuffer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCTableBuffer;
  END_STRUCT;
  CltChCmd__Lse : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_Lse;
  END_STRUCT;
  CltChCmd__MultiTask : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_MultiTask;
  END_STRUCT;
  CltChCmd__OSKernel : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_OSKernel;
  END_STRUCT;
  CltChCmd__OsziLSEBackground : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_OsziLSEBackground;
  END_STRUCT;
  CltChCmd__SerLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_SerLib;
  END_STRUCT;
  CltChCmd__SerLibCSI : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_SerLibCSI;
  END_STRUCT;
  CltChCmd__StdLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_StdLib;
  END_STRUCT;
  SvrChCmd_DATE_LSL : STRUCT
    pMeth : ^CMDMETH;
    dData : DATE_LSL;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__SysDateTime2 : STRUCT
    pCh : ^SvrChCmd_DATE_LSL;
    dData : DATE_LSL;
    pCmd : ^_SysDateTime2;
  END_STRUCT;
  CltChCmd__SysMsg : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_SysMsg;
  END_STRUCT;
  CltChCmd__TaskObjectControl : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_TaskObjectControl;
  END_STRUCT;
  CltChCmd__VaranDriveBase : STRUCT
    pCh : ^SvrChCmd_t_e_VaranErrors;
    dData : t_e_VaranErrors;
    pCmd : ^_VaranDriveBase;
  END_STRUCT;
  CltChCmd_ASCII_BIN : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^ASCII_BIN;
  END_STRUCT;
  CltChCmd_AssemblyDbV2 : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^AssemblyDbV2;
  END_STRUCT;
  CltChCmd_AssemblyOneProdRuleV2 : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^AssemblyOneProdRuleV2;
  END_STRUCT;
  SvrChCmd_BDINT : STRUCT
    pMeth : ^CMDMETH;
    dData : BDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_BDINT : STRUCT
    pCh : ^SvrChCmd_BDINT;
    dData : BDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  CltChCmd_calcComplete : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^calcComplete;
  END_STRUCT;
  CltChCmd_calcOperationListV2 : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^calcOperationListV2;
  END_STRUCT;
  CltChCmd_CanDriverBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^CanDriverBase;
  END_STRUCT;
  CltChCmd_CanOpenBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^CanOpenBase;
  END_STRUCT;
  CltChCmd_cmBlower : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^cmBlower;
  END_STRUCT;
  CltChCmd_cmCil : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^cmCil;
  END_STRUCT;
  CltChCmd_cmMotor : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^cmMotor;
  END_STRUCT;
  CltChCmd_cmMultipleCil : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^cmMultipleCil;
  END_STRUCT;
  CltChCmd_cmServo : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^cmServo;
  END_STRUCT;
  CltChCmd_cntrAmount : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^cntrAmount;
  END_STRUCT;
  CltChCmd_cntrDistance : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^cntrDistance;
  END_STRUCT;
  CltChCmd_ConfigDefBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^ConfigDefBase;
  END_STRUCT;
  CltChCmd_Controller : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Controller;
  END_STRUCT;
  CltChCmd_convertOperationListToSLinesV2 : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^convertOperationListToSLinesV2;
  END_STRUCT;
  SvrChCmd_UDINT : STRUCT
    pMeth : ^CMDMETH;
    dData : UDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_CriticalSection : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^CriticalSection;
  END_STRUCT;
  SvrChCmd_IO_State : STRUCT
    pMeth : ^CMDMETH;
    dData : IO_State;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_CSI022_Base : STRUCT
    pCh : ^SvrChCmd_IO_State;
    dData : IO_State;
    pCmd : ^CSI022_Base;
  END_STRUCT;
  CltChCmd_dbSettings : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^dbSettings;
  END_STRUCT;
  CltChCmd_DiasMaster : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^DiasMaster;
  END_STRUCT;
  CltChCmd_DiasMasterC : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^DiasMasterC;
  END_STRUCT;
  CltChCmd_DiasMasterPostScan : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^DiasMasterPostScan;
  END_STRUCT;
  CltChCmd_DINT : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  CltChCmd_EditString : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^EditString;
  END_STRUCT;
  CltChCmd_EEPROM : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^EEPROM;
  END_STRUCT;
  CltChCmd_emBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^emBase;
  END_STRUCT;
  CltChCmd_emPressureRoller : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^emPressureRoller;
  END_STRUCT;
  CltChCmd_emWagon : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^emWagon;
  END_STRUCT;
  CltChCmd_File_IO : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^File_IO;
  END_STRUCT;
  CltChCmd_FileBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^FileBase;
  END_STRUCT;
  CltChCmd_GetBroadCastData : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^GetBroadCastData;
  END_STRUCT;
  CltChCmd_GlobalList : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^GlobalList;
  END_STRUCT;
  CltChCmd_Graphic : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Graphic;
  END_STRUCT;
  CltChCmd_Hub_Base : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Hub_Base;
  END_STRUCT;
  CltChCmd_Hub_Base_Root : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Hub_Base_Root;
  END_STRUCT;
  CltChCmd_HwcLogging : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^HwcLogging;
  END_STRUCT;
  CltChCmd_HwControl : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^HwControl;
  END_STRUCT;
  CltChCmd_HwControlBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^HwControlBase;
  END_STRUCT;
  CltChCmd_HWKVarSizeFIFO : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^HWKVarSizeFIFO;
  END_STRUCT;
  CltChCmd_HWRtPostScan : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^HWRtPostScan;
  END_STRUCT;
  CltChCmd_I2CCDIAS : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^I2CCDIAS;
  END_STRUCT;
  CltChCmd_Lees10Ingangenin : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Lees10Ingangenin;
  END_STRUCT;
  CltChCmd_Logic_Or_2 : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Logic_Or_2;
  END_STRUCT;
  CltChCmd_mainControl : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^mainControl;
  END_STRUCT;
  CltChCmd_MerkerEx : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^MerkerEx;
  END_STRUCT;
  CltChCmd_MillingProgsDbV2 : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^MillingProgsDbV2;
  END_STRUCT;
  CltChCmd_MillLine : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^MillLine;
  END_STRUCT;
  CltChCmd_MillPlane : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^MillPlane;
  END_STRUCT;
  CltChCmd_MillPlanes : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^MillPlanes;
  END_STRUCT;
  CltChCmd_MotorParaBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^MotorParaBase;
  END_STRUCT;
  CltChCmd_OperationDataV2 : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^OperationDataV2;
  END_STRUCT;
  CltChCmd_OperationLineV2 : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^OperationLineV2;
  END_STRUCT;
  CltChCmd_ProductsDbV2 : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^ProductsDbV2;
  END_STRUCT;
  CltChCmd_ProfileCommandStatus : STRUCT
    pCh : ^SvrChCmd_ProfileCommandStatus;
    dData : ProfileCommandStatus;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  CltChCmd_Ram : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Ram;
  END_STRUCT;
  CltChCmd_RAMex : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^RAMex;
  END_STRUCT;
  CltChCmd_RamFile : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^RamFile;
  END_STRUCT;
  CltChCmd_RamSregels : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^RamSregels;
  END_STRUCT;
  CltChCmd_readInGlobalList : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^readInGlobalList;
  END_STRUCT;
  CltChCmd_SafetyManager : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SafetyManager;
  END_STRUCT;
  CltChCmd_SCBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SCBase;
  END_STRUCT;
  CltChCmd_ScreenCtrl : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^ScreenCtrl;
  END_STRUCT;
  CltChCmd_SDCIClassIFM2330 : STRUCT
    pCh : ^SvrChCmd_t_e_VaranErrors;
    dData : t_e_VaranErrors;
    pCmd : ^SDCIClassIFM2330;
  END_STRUCT;
  CltChCmd_SDCIClassIFM_AL2401 : STRUCT
    pCh : ^SvrChCmd_t_e_VaranErrors;
    dData : t_e_VaranErrors;
    pCmd : ^SDCIClassIFM_AL2401;
  END_STRUCT;
  CltChCmd_SDCIDevice : STRUCT
    pCh : ^SvrChCmd_t_e_VaranErrors;
    dData : t_e_VaranErrors;
    pCmd : ^SDCIDevice;
  END_STRUCT;
  CltChCmd_SDCIDevice_AsyncPara : STRUCT
    pCh : ^SvrChCmd_iprStates;
    dData : iprStates;
    pCmd : ^SDCIDevice_AsyncPara;
  END_STRUCT;
  CltChCmd_SDCIPort : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SDCIPort;
  END_STRUCT;
  CltChCmd_SdiasBase : STRUCT
    pCh : ^SvrChCmd_t_e_VaranErrors;
    dData : t_e_VaranErrors;
    pCmd : ^SdiasBase;
  END_STRUCT;
  CltChCmd_SdiasHubBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SdiasHubBase;
  END_STRUCT;
  CltChCmd_SdiasManager : STRUCT
    pCh : ^SvrChCmd_t_e_VaranErrors;
    dData : t_e_VaranErrors;
    pCmd : ^SdiasManager;
  END_STRUCT;
  CltChCmd_SdiasSafetyManager : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SdiasSafetyManager;
  END_STRUCT;
  CltChCmd_SdiasSafetyManagerFSoE : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SdiasSafetyManagerFSoE;
  END_STRUCT;
  CltChCmd_SdiasUartHandler : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SdiasUartHandler;
  END_STRUCT;
  CltChCmd_SigCLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SigCLib;
  END_STRUCT;
  CltChCmd_sLineHandler : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^sLineHandler;
  END_STRUCT;
  CltChCmd_String : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^String;
  END_STRUCT;
  CltChCmd_StringInternal : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^StringInternal;
  END_STRUCT;
  CltChCmd_StringRAM : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^StringRAM;
  END_STRUCT;
  CltChCmd_SyncCall : STRUCT
    pCh : ^SvrChCmd_IO_State;
    dData : IO_State;
    pCmd : ^SyncCall;
  END_STRUCT;
  CltChCmd_System : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^System;
  END_STRUCT;
  CltChCmd_t_e_VaranErrors : STRUCT
    pCh : ^SvrChCmd_t_e_VaranErrors;
    dData : t_e_VaranErrors;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  CltChCmd_tMyBDintTODint : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^tMyBDintTODint;
  END_STRUCT;
  CltChCmd_ToolsDb : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^ToolsDb;
  END_STRUCT;
  CltChCmd_Uitv_Regel : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Uitv_Regel;
  END_STRUCT;
  CltChCmd_unitBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^unitBase;
  END_STRUCT;
  CltChCmd_Varan_Base : STRUCT
    pCh : ^SvrChCmd_t_e_VaranErrors;
    dData : t_e_VaranErrors;
    pCmd : ^Varan_Base;
  END_STRUCT;
  CltChCmd_VaranManager_Base : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^VaranManager_Base;
  END_STRUCT;
  CltChCmd_WatchdogDias : STRUCT
    pCh : ^SvrChCmd_IO_State;
    dData : IO_State;
    pCmd : ^WatchdogDias;
  END_STRUCT;
  SvrCh__CommandList_PTofCls__LMCAxisBase : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAxisBase::_CommandList;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__DRIVETYPE : STRUCT
    pMeth : ^CHMETH;
    dData : _DRIVETYPE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__FSM_UDP_ERROR_PTofCls_SafetyUDP : STRUCT
    pMeth : ^CHMETH;
    dData : SafetyUDP::_FSM_UDP_ERROR;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__FSM_UDP_USER_PTofCls_SafetyUDP : STRUCT
    pMeth : ^CHMETH;
    dData : SafetyUDP::_FSM_UDP_USER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__I_HC_Type : STRUCT
    pMeth : ^CHMETH;
    dData : _I_HC_Type;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__INITSTEPS_PTofCls_SafetyUDP : STRUCT
    pMeth : ^CHMETH;
    dData : SafetyUDP::_INITSTEPS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_CMDERROR : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_CMDERROR;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_ERROR : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_ERROR;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_ERROR_CONFIG : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_ERROR_CONFIG;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_MOVE_RELATIVE_MODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_MOVE_RELATIVE_MODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_MOVEDIRECTION : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_MOVEDIRECTION;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_MOVEPROFILE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_MOVEPROFILE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_OPMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_OPMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_POSMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_POSMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_POWER_OFF_MODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_POWER_OFF_MODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_REFMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_REFMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_SETPARAMETER : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_SETPARAMETER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_SETPOSITION : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_SETPOSITION;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_SETSWENDPOS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_SETSWENDPOS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_STATUS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_STATUS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCCONTROLLERTYPE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCCONTROLLERTYPE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROF_OPMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROF_OPMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFCIRCLEDEF : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFCIRCLEDEF;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFCMDCONFIG : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFCMDCONFIG;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFCMDTYPES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFCMDTYPES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFERRORTYPES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFERRORTYPES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFERRWARNCONFIG : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFERRWARNCONFIG;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFILESTATES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFILESTATES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFMOVEPROFILE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFMOVEPROFILE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFPARAMETER : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFPARAMETER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFPARAMETERAXIS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFPARAMETERAXIS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFPARAMETERGROUPS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFPARAMETERGROUPS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFTRANSMODES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFTRANSMODES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__SDDAXISSTATE : STRUCT
    pMeth : ^CHMETH;
    dData : _SDDAXISSTATE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__SDDUSERCMD : STRUCT
    pMeth : ^CHMETH;
    dData : _SDDUSERCMD;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_CanDeviceStateTxt : STRUCT
    pMeth : ^CHMETH;
    dData : CanDeviceStateTxt;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_DS402_Control : STRUCT
    pMeth : ^CHMETH;
    dData : DS402_Control;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_DS402_State : STRUCT
    pMeth : ^CHMETH;
    dData : DS402_State;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_eMillToolComp : STRUCT
    pMeth : ^CHMETH;
    dData : eMillToolComp;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_eMillType : STRUCT
    pMeth : ^CHMETH;
    dData : eMillType;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_eModePML : STRUCT
    pMeth : ^CHMETH;
    dData : eModePML;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_eStatePML : STRUCT
    pMeth : ^CHMETH;
    dData : eStatePML;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_eTypeMillProg : STRUCT
    pMeth : ^CHMETH;
    dData : eTypeMillProg;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_EventTypeTxt_PTofCls_SCBase : STRUCT
    pMeth : ^CHMETH;
    dData : SCBase::EventTypeTxt;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_feedPos : STRUCT
    pMeth : ^CHMETH;
    dData : feedPos;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_motorPos : STRUCT
    pMeth : ^CHMETH;
    dData : motorPos;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_pcPlaneType : STRUCT
    pMeth : ^CHMETH;
    dData : pcPlaneType;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_pcUnitTypes : STRUCT
    pMeth : ^CHMETH;
    dData : pcUnitTypes;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_SafetyConfigStateType : STRUCT
    pMeth : ^CHMETH;
    dData : SafetyConfigStateType;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_servoPos : STRUCT
    pMeth : ^CHMETH;
    dData : servoPos;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_bdOptionBits_PTofCls_SdiasUartHandler : STRUCT
    pMeth : ^CHMETH;
    dData : SdiasUartHandler::t_bdOptionBits;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_e_VaranErrors : STRUCT
    pMeth : ^CHMETH;
    dData : t_e_VaranErrors;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_FaultFlagSvr_PTofCls_SDCIDevice : STRUCT
    pMeth : ^CHMETH;
    dData : SDCIDevice::t_FaultFlagSvr;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_SDCIPortStateBits_PTofCls_SdiasSDCIMaster : STRUCT
    pMeth : ^CHMETH;
    dData : SdiasSDCIMaster::t_SDCIPortStateBits;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_SDCIRetCode_PTofCls_SdiasSDCIMaster : STRUCT
    pMeth : ^CHMETH;
    dData : SdiasSDCIMaster::t_SDCIRetCode;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_SDIAS_ErrorBits_AM221_PTofCls_AM221 : STRUCT
    pMeth : ^CHMETH;
    dData : AM221::t_SDIAS_ErrorBits_AM221;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_SDIAS_ErrorBits_AM441_PTofCls_AM441 : STRUCT
    pMeth : ^CHMETH;
    dData : AM441::t_SDIAS_ErrorBits_AM441;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_TIME_LSL : STRUCT
    pMeth : ^CHMETH;
    dData : TIME_LSL;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_tMyBDint : STRUCT
    pMeth : ^CHMETH;
    dData : tMyBDint;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_Units : STRUCT
    pMeth : ^CHMETH;
    dData : Units;
    pDsc : ^SVRDSC;
  END_STRUCT;
END_TYPE
